# Generated by Django 6.1.1 on 2026-09-17 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=100)),
                ('blood_group', models.CharField(max_length=5)),
                ('units', models.IntegerField()),
                ('hospital', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=15)),
            ],
        ),
    ]
