# Generated by Django 6.1.1 on 2026-09-17 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_bloodstock'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='units',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='patient',
            name='units',
            field=models.IntegerField(default=1),
        ),
    ]
