# Generated by Django 6.1.1 on 2026-09-18 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_patient_blood_group_remove_patient_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloodrequest',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='patient_id',
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='patient_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='request_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
