# Generated by Django 6.1.1 on 2026-09-19 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_bloodrequest_phone_remove_patient_patient_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
